### ISSUE TITLE
Subband Imaging

### ISSUE THREAD

**Issue by joesbright** [saopicc/DDFacet#14]
Hi,

I might be missing something here, but is there an option in DDFacet for producing a set of images in some number of subbands over the total bandwidth?

Thanks a lot,
Joe

**Comment by o-smirnov** [comment]
--Freq-NBand. :)

You might also want to check your output cube setting, to make sure the
cubes you want are actually saved.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by joesbright** [comment]
Thanks a lot Oleg,

I wasn't outputting the cube correctly.
