### ISSUE TITLE
worker killed suddenly

### ISSUE THREAD

**Issue by Arnab-half-blood-prince** [saopicc/DDFacet#22]
Hi,
I have been trying to image with DDFacet. 
The data is of 400 MHz bandwidth and ~6 hours is the total observation time. 
But, the worker is killed suddenly. I am not sure why it is that. Is it because of memory and cpus? 
I am running this in a 256 GB memory and 96 cores machine. I am using stimela interface to run ddfacet. 

The log and parset are being attached. 
[ddfacet_pre_peel.log](https://github.com/saopicc/DDFacet/files/5317455/ddfacet_pre_peel.log)
[ddfacet.parset.log](https://github.com/saopicc/DDFacet/files/5317458/ddfacet.parset.log)

**Comment by o-smirnov** [comment]
The log has the answers you seek:
```
 - 10:37:44 - DDFacet            | WARNING: max shared memory size is only 6% of total RAM size.
            This can cause problems for large imaging jobs. A setting of 90% is recommended for 
            DDFacet and killMS. If your processes keep failing with SIGBUS or "bus error" messages,
            it is most likely for this reason. You can change the memory size by running
                $ sudo mount -o remount,size=90% /dev/shm
            To make the change permanent, edit /etc/defaults/tmps, and add a line saying "SHM_SIZE=90%".
            
 - 10:37:44 - DDFacet            | WARNING: /sbin/sysctl vm.max_map_count failed. Unable to check this setting.
 - 10:37:44 - DDFacet            | WARNING: your system has a limit on memory locks configured.
            This may possibly slow down DDFacet performance. You can try removing the limit by running
                $ ulimit -l unlimited
            If this gives an "operation not permitted" error, you can try to bribe, beg or threaten 
            your friendly local sysadmin into doing
                # echo "*        -   memlock     unlimited" >> /etc/security/limits.conf
```

**Comment by Arnabiitindore** [comment]
I tried with 90% memory. But. now I am getting a different problem in the beginning of the major cycle. 
The log file is attached. 
[image_DI.log](https://github.com/saopicc/DDFacet/files/5338289/image_DI.log)

**Comment by o-smirnov** [comment]
Great, so you've got a dirty image, that's progress!

Looks like it's falling over in the automask. @cyriltasse any suggestions? Also @cyriltasse could you please add @Arnabiitindore to the private development repo?

```
 - 10:08:39 - MaskMachine        | Computing Mask
 - 10:08:39 - MaskMachine        | (re-)Computing noise map
 - 10:08:39 - MaskMachine        |   Running Brutal deconvolution...
 - 10:08:39 - ClassPSFServer     | Using peak-normalised PSFs
 - 10:08:39 - ClassPSFServer     | Using peak-normalised PSFs
 - 10:08:39 - DDFacet            | Traceback (most recent call last):
  File "/home/ramij/venv3/bin/DDF.py", line 454, in <module>
    main(OP, messages)
  File "/home/ramij/venv3/bin/DDF.py", line 288, in main
    Imager.main()
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1145, in main
    self.MaskMachine.updateMask(self.DicoDirty)
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/ClassMaskMachine.py", line 80, in updateMask
    self.ImageNoiseMachine.calcNoiseMap(DicoResidual)
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/ClassImageNoiseMachine.py", line 173, in calcNoiseMap
    self.giveBrutalRestored(DicoResidual)
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/ClassImageNoiseMachine.py", line 203, in giveBrutalRestored
    GridFreqs=self.GridFreqs, DegridFreqs=self.DegridFreqs, RefFreq=self.RefFreq)
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/HOGBOM/ClassImageDeconvMachineHogbom.py", line 126, in Init
    weights=kwargs["PSFVar"]["WeightChansImages"], PSFServer=self.PSFServer)
  File "/home/ramij/venv3/lib/python3.6/site-packages/DDFacet/Imager/HOGBOM/ClassModelMachineHogbom.py", line 72, in setFreqMachine
    self.DicoSMStacked["RefFreq"], self.GD,
KeyError: 'RefFreq'
```

**Comment by cyriltasse** [comment]
This looks like an old bug with the reffreq key... @o-smirnov  yes I invite @Arnabiitindore !

**Comment by o-smirnov** [comment]
OK @Arnabiitindore maybe pull the master branch from the private repo, and see if the bug persists there.

**Comment by Arnabiitindore** [comment]
Ok. 
I have used the latest DDFACET version. The RestFreq problem is still there. But, when I used a esternal mask file. It worked. But the image I got is really bad in comparison with last wsclean run. I have only done the 2GC till now. The image and mask file is being attached. 

Maybe I am worng in some parameters in ddfacet. I used : DDF.py --Output-Name=image_DI --Data-MS CDFS_S01_22JAN.ms --Deconv-PeakFactor 0.15 --Data-ColName DATA --Parallel-NCPU=40  --Deconv-CycleFactor=0 --Deconv-MaxMajorIter=6 --Deconv-MaxMinorIter 100000 --Deconv-Mode Hogbom --Hogbom-PolyFitOrder 3 --Weight-Robust -1.0 --Image-NPix=8192  --Output-Also onNeds --Image-Cell 0.5 --Facets-NFacets=11  --Freq-NDegridBand 4  --Deconv-RMSFactor=3.000000 --Data-Sort 1 --Cache-Dir=. --Freq-NBand=2 --Mask-External='CDFS_S01-MFS-image.mask1.fits' --Mask-Auto 0 --Cache-Reset 0  --Log-Boring=1

It is a 400 MHz BW, 2048 chans uGMRT data.
![Screenshot from 2020-10-07 16-15-56](https://user-images.githubusercontent.com/20695190/95321264-6cf60800-08b8-11eb-827b-409f3450a7f8.png)
[image.log](https://github.com/saopicc/DDFacet/files/5339968/image.log)

 

Can you suggest if I am wrong somewhere. 
![Screenshot from 2020-10-07 16-05-36](https://user-images.githubusercontent.com/20695190/95320897-d295c480-08b7-11eb-8cfc-1077e3d33d5d.png)
![Screenshot from 2020-10-07 16-05-59](https://user-images.githubusercontent.com/20695190/95320899-d45f8800-08b7-11eb-9e85-d2c8bc31202d.png)

**Comment by cyriltasse** [comment]
Ok so the problem is automasking with `--Deconv-Mode Hogbom`, @bennahugo any idea?

**Comment by Arnabiitindore** [comment]
Ok. I will try SSD deconvolution then. 
But even with Hogbom, when I pass an external mask fits based on the last wsclean MFS image, then it worked. 
I will let you know.

**Comment by bennahugo** [comment]
There is no automasking for Hogbom

**Comment by bennahugo** [comment]
Do note that the wsclean and ddfacet image sizes are not the same (even if you tell it to do a certain number of pixels). Your mask needs to be interpolated to the right number of pixels prior to imaging, or you need to create a mask from a ddfacet image. I don't think the imager will bomb out if the mask is not the right size - you will just not get sensible answers

**Comment by Arnabiitindore** [comment]
Yes. I understood. A blind DDFACET is required to proceed with KMS and masking. I have gone through several issues posted in ddfacet github and understood the problem (I guess). 

I will give it a try and let you know.  DD-cal with killms is also required to remove those last 2GC image (wsclean).

**Comment by bennahugo** [comment]
We really should check the WCS of the external mask @cyriltasse. It is not the first time this has caused first time users pain.

**Comment by cyriltasse** [comment]
@bennahugo yeah I agree that's a good point...

**Comment by Arnabiitindore** [comment]
Hi,
It is done with SSD and auto masking. 
![Screenshot from 2020-10-09 14-25-07](https://user-images.githubusercontent.com/20695190/95563657-5330fe00-0a3b-11eb-8010-453985eb4995.png)

I still require to apply killms to solve DD issues.
