### ISSUE TITLE
DDFacet Installation errors on crosby

### ISSUE THREAD

**Issue by Kincaidr** [saopicc/DDFacet#23]
I am trying to install ddfacet on crosby using the following method(with venv activated):

![image](https://user-images.githubusercontent.com/53697426/98940554-cd99e580-24f3-11eb-938f-9c36d280e62c.png)

The error arises when i do : pip install -e DDFacet/

See below:

kincaid@crosby:~$ pip install -e DDFacet/
Obtaining file:///home/kincaid/DDFacet
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/kincaid/ddfacet/bin/python /home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpfm9yjkwp
       cwd: /home/kincaid/DDFacet
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/kincaid/ddfacet/bin/python /home/kincaid/ddfacet/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpfm9yjkwp Check the logs for full command output.
(ddfacet) kincaid@crosby:~$

**Comment by Kincaidr** [comment]
The error was to do with my venv: I was doing the installation with a specific ddfacet venv( virtualenv --system-site-packages ddfacet ). When i switched to my normal venv , the one in which caracal, cubical , etc where all installed it worked. I am still not sure why this worked though, since the ddfacet web-page instructs you to do instillation with a specific ddfacet venv.

**Comment by o-smirnov** [comment]
> since the ddfacet web-page instructs you to do instillation with a specific ddfacet venv.

That recommendation is just to keep users out of trouble... the more packages you install into one venv, the more chances of some library version incompatibility. But as long as it works for you, it's all good.

You could also try creating a venv without --system-site-packages -- that gives you the blankest of blank slates -- to see if the install works there.
