### ISSUE TITLE
install requirements too strict

### ISSUE THREAD

**Issue by gijzelaerr** [saopicc/DDFacet#3]
Currently the `setup.py` specifies quite some specific requirements. That is not going to work for a package. I get the impression somebody just ran `pip freeze` and then copy pasted this in the install requires field. That is what a `requirements.txt` usually is used for. `setup.py `should be a bit more general, and just specify the version that the software should work with (or explicitly doesn't).

Other questions are:
 * I don't think `Cython` is required runtime and installation time. the correct way to bundle Cython code is to just bundle the code with the generated C code, so the end user only needs to compile that: http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules
 * `numpy` rc? That sounds scary. doesn't it just work with 1.11
 * `nose`? probably not required during runtime, only testing?
 * `ipdb`? probably only required during development?
 * `pyfits` is replaced by `astropy.io.fits`, which is also a dependency.
 * Are the packages `SharedArray`, `Polygon2` and` py-cpuinfo` absolutely required or 'nice to have'? There are no debian packages available for these, so this would imply that I need to package them. Which implies that potentially the time I have to spend on this all is going to explode exponentially.

**Comment by o-smirnov** [comment]
Your impression re: pip freeze is correct. I remember moaning at @bennahugo about that. Let us do away with this too-specific silliness.

* Happy with whatever cython solution is recommended.
* It should work with numpy 1.11.
* nose/ipdb not required
* we can just replace ``import pyfits`` with  ``import astro.io.fits as pyfits`` and everything magically works, correct?
* ``SharedArray`` and ``Polygon2`` are must-haves. The first one will be trivial to package, I promise you. No idea about the second one...
* ``py-cpuinfo`` can be reduced to a "nice to have" with some recoding, but before we do that, can you check if packaging it is really a mission?

**Comment by bennahugo** [comment]
@o-smirnov not sure about removing pyfits. As far as I recall we've seen some API changes with a tigger issue a while ago? Keeping it in for now as there is a python-pyfits is on Debian

**Comment by mhardcastle** [comment]
It's crazy to have astropy as a dependency and also pyfits, though: I think that's @gijzelaerr's point.
Happy to do the work of removing pyfits if you like (since it was me who dragged in astropy...)

**Comment by o-smirnov** [comment]
The API changes @bennahugo refers to were an issue with ``pyfits`` itself already, since they got rid of an older interface at some point. I think we've worked our way through them by now. To first order I'd just replace ``import pyfits`` with ``import astro.io.fits as pyfits``, and see if the tests still pass. Since @mhardcastle volunteered, I'm happy to let him have a go at it.

**Comment by mhardcastle** [comment]
@o-smirnov In fact it turns out that I already eradicated the use of pyfits when I updated the image writing code. We've been running astropy only for months. It just needs to be removed from setup.py.

**Comment by bennahugo** [comment]
Non-strict requirements fixed in #4

**Comment by bennahugo** [comment]
Stale - unfortunately for release builds we are pinning versions to guard against the software falling over due to upstream changes. This has been the practice for a while now.
