### ISSUE TITLE
/sbin/sysctl vm.max_map_count failed. Unable to check this setting

### ISSUE THREAD

**Issue by AlexKurek** [saopicc/DDFacet#39]
Just reporting: this is never working insider DDF Singularity container:
` - 09:52:51 - DDFacet            | [1m[91mWARNING: /sbin/sysctl vm.max_map_count failed. Unable to check this setting.[0m[0m`

```
Singularity> /bin/sysctl vm.max_map_count
bash: /bin/sysctl: No such file or directory
```
Solution:
https://stackoverflow.com/questions/71524077/how-to-verify-if-in-singularityapptainer-container

**Comment by mhardcastle** [comment]
WFM:

Singularity> /sbin/sysctl vm.max_map_count
vm.max_map_count = 65530

(note /bin and /sbin not the same)
