### ISSUE TITLE
worker 'comp00' killed by signal SIGKILL

### ISSUE THREAD

**Issue by Mohitpanwar123** [saopicc/DDFacet#43]
getting error while processing  single ms file from ToSS Second Data release DR2.  log file is also attached.
[image_DI.log](https://github.com/saopicc/DDFacet/files/11261784/image_DI.log)

**Comment by mhardcastle** [comment]
Most likely a memory error. If you have the ability to check the machine logs, see if the OOM killer has run. DDFacet needs a lot of RAM for these large images.

**Comment by Mohitpanwar123** [comment]
It makes sense that this error is due to a memory error but for processing a small data set(in my case, 2.5 GB data size), will you please let me know what should be the system requirements in terms of memory(RAM and other memories if needed) so that DDFacet run successfully on few GB LOFAR data set. Any additional information regarding the same will be beneficial for me.
