### ISSUE TITLE
ValueError: Cannot convert input correlations to desired output Stokes parameters

### ISSUE THREAD

**Issue by samit97** [saopicc/DDFacet#47]
Hi,
I am trying to run the SKA dataset, which has only single polarization. I am getting an error when running DDF.py: "ValueError: Cannot convert input correlations to desired output Stokes parameters".  

The error :
 - 17:11:19 - AsyncProcessPool             [0.2/0.3 62.3/62.3 67.3Gb] process comp09: exception raised processing job FM.Grid.1.1:F9: Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Other/AsyncProcessPool.py", line 870, in _dispatch_job
    result = call(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Imager/ClassFacetMachine.py", line 1549, in _grid_worker
    GridMachine.put(times, uvwThis, visThis, flagsThis, A0A1, W,
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Imager/ClassDDEGridMachine.py", line 793, in put
    gridfun(Grid,
ValueError: Cannot convert input correlations to desired output Stokes parameters.

**Comment by bennahugo** [comment]
Full backtrace please. Note it is numerically impossible to convert XX or YY into stokes I. We only support XX YY or XX XY YX YY or I. You may need to adjust your ::POLARIZATION table accordingly

**Comment by bennahugo** [comment]
See casacore documentation on enumerations: https://casacore.github.io/casacore/Stokes_8h_source.html

**Comment by cyriltasse** [comment]
@samit97 in ipython/python you can check what polarisation is available in your metadata:

```
from pyrap.tables import table
t=table("<yourMSName>/POLARIZATION/")
print(t.getcol("CORR_TYPE"))
print(t.getcol("CORR_PRODUCT"))
```

and return the result here

**Comment by samit97** [comment]
I am getting this result :
CORR_TYPE = [[9]]
and "CORR_PRODUCT = [[0 0]]

Successful readonly open of default-locked table ZW3_IFRQ_0000.ms/POLARIZATION/: 4 columns, 1 rows
In [3]: print(t.getcol("CORR_TYPE"))
[[9]]
In [4]: print(t.getcol("CORR_PRODUCT"))
[[[0 0]]]

**Comment by bennahugo** [comment]
Ok 9 means XX. This cannot be converted to stokes I. We don't directly support XX imaging because it is not a valid stokes product. You can change this to correlation type 1 instead (ie. you define it as an unpolarized total intensity product) and things should work as expected.

**Comment by samit97** [comment]
Thanks. Please share some links so that I can modify the msfile.

**Comment by cyriltasse** [comment]
It's a problem with your MS file and not with `DDFacet`. You're asking it to do an impossible conversion. So you have to hack your MS and write in it. This kind of thing you have in principle to learn to do when you work with radiointerferometric dataset (read from, write to):

```
from pyrap.tables import table
# open your table object
t=table("<yourMSName>/POLARIZATION/",readonly=False)
# read
c=t.getcol("CORR_TYPE")
# replace with 1 - see benna's link
c.fill(1)
# write in
t.putcol("CORR_TYPE",c)
# close the table object
t.close()
```

You should also ask yourself what happened with YY?
